### ISSUE TITLE
Dashboard template - ignore "instance"

### ISSUE THREAD

**Issue by V3XATI0N** [wbollock/nagios_exporter#28]
this may be out of scope for this project, but I containerized the nagios_exporter and I'm running it in k8s - the problem there is that I lose data continuity every time the pod is replaced or restarted because the data in the daashboard is tied to "instance", which is irrelevant for my use case. Any ideas on how I can just skip that distinction?

**Comment by wbollock** [comment]
Hey @V3XATI0N , happy to hear you're using this project!!

In this case I would recommend one of two things:

1. Relabel **instance** at scrape time to a static value that represents your Nagios instance

e.g:
```
relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'nagios_V3XATI0N'
```

By default I'm fairly sure __address__ gets relabed into instance, which is where your pod hostname comes into play.

2. Simply drop all instance labels from the dashboard.

I should probably be using jsonnet to template out the Grafana dashboard instead so it's more customizable. However you might be able to just find and remove `instance=\"$instance\"` and `instance=\"$instance\",` from the PromQL queries in each panel to make the dashboard instance independent. My homelab is a bit broken right now so can't test it for you but the dashboard I'm linking below may work.

https://gist.github.com/wbollock/86b6b0ad705a0c26ecb7bd6a48e7ac51

Admittedly I haven't had this specific issue before but I hope this helps! Let me know how it goes and if you have any other feature requests

**Comment by wbollock** [comment]
you many want to try re-labeling like this too: https://grafana.com/blog/2022/03/21/how-relabeling-in-prometheus-works/#labelmap

hope this helps! when/if I get the dashboard templated with jsonnet that should help a bunch also to make mass adjustments
