### ISSUE TITLE
icingastats parsing leads to incorrect nagios_services_checked_total metric

### ISSUE THREAD

**Issue by anarcat** [wbollock/nagios_exporter#45]
Here we're running an old Icinga instance. I setup this exporter in the hope of tracking our (eventual) conversion to prometheus and (in the meantime) track its performance.

The bottom panels look like this:

![image](https://github.com/wbollock/nagios_exporter/assets/796623/f5168fb0-492c-459a-8e96-6c511d1dd82c)

I have modified the titles to say "last hour", since this is what I think the metric is based off, from reading the source code:

https://github.com/wbollock/nagios_exporter/blob/7e07acae1b52fbb933f6a147177c8dcf1dc1c993/nagios_exporter.go#L978

Yet even that doesn't seem to match the output of icingastats:

```
root@hetzner-hel1-01:~# icingastats 

Icinga Stats 1.14.2
Copyright (c) 2009 Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 12-20-2017
License: GPL

CURRENT STATUS DATA
------------------------------------------------------
Status File:                            /var/lib/icinga/status.dat
Status File Age:                        0d 0h 0m 3s
Status File Version:                    1.14.2

Program Running Time:                   0d 2h 40m 48s
Icinga PID:                             1182
Used/High/Total Command Buffers:        0 / 0 / 4096

Total Services:                         4403
Services Checked:                       4403
Services Scheduled:                     4403
Services Actively Checked:              4403
Services Passively Checked:             0
Total Service State Change:             0.000 / 19.610 / 0.128 %
Active Service Latency:                 0.002 / 0.351 / 0.136 sec
Active Service Execution Time:          0.019 / 6.920 / 0.415 sec
Active Service State Change:            0.000 / 19.610 / 0.128 %
Active Services Last 1/5/15/60 min:     241 / 1184 / 3570 / 4227
Passive Service Latency:                0.000 / 0.000 / 0.000 sec
Passive Service State Change:           0.000 / 0.000 / 0.000 %
Passive Services Last 1/5/15/60 min:    0 / 0 / 0 / 0
Services Ok/Warn/Unk/Crit:              4382 / 18 / 0 / 3
Services Flapping:                      2
Services In Downtime:                   0

Total Hosts:                            96
Hosts Checked:                          96
Hosts Scheduled:                        96
Hosts Actively Checked:                 96
Host Passively Checked:                 0
Total Host State Change:                0.000 / 11.050 / 0.115 %
Active Host Latency:                    0.094 / 0.376 / 0.225 sec
Active Host Execution Time:             0.037 / 0.206 / 0.111 sec
Active Host State Change:               0.000 / 11.050 / 0.115 %
Active Hosts Last 1/5/15/60 min:        13 / 90 / 96 / 96
Passive Host Latency:                   0.000 / 0.000 / 0.000 sec
Passive Host State Change:              0.000 / 0.000 / 0.000 %
Passive Hosts Last 1/5/15/60 min:       0 / 0 / 0 / 0
Hosts Up/Down/Unreach:                  96 / 0 / 0
Hosts Flapping:                         0
Hosts In Downtime:                      0

Active Host Checks Last 1/5/15 min:     14 / 92 / 286
   Scheduled:                           14 / 91 / 276
   On-demand:                           0 / 1 / 10
   Parallel:                            14 / 91 / 276
   Serial:                              0 / 0 / 0
   Cached:                              0 / 1 / 10
Passive Host Checks Last 1/5/15 min:    0 / 0 / 0
Active Service Checks Last 1/5/15 min:  246 / 1195 / 3771
   Scheduled:                           246 / 1195 / 3771
   On-demand:                           0 / 0 / 0
   Cached:                              0 / 0 / 0
Passive Service Checks Last 1/5/15 min: 0 / 0 / 0

External Commands Last 1/5/15 min:      0 / 0 / 0
```

Or, to put it in a shorter version:

```
root@hetzner-hel1-01:~# icingastats -d NUMSVCACTCHK60M -m -D,
4227,
```

That doesn't map at all to the actual value returned by the exporter, which is now zero:

```
root@hetzner-hel1-01:~# curl -sSL localhost:9927/metrics | grep nagios_services_checked_total
# HELP nagios_services_checked_total Amount of services checked
# TYPE nagios_services_checked_total gauge
nagios_services_checked_total{check_type="active"} 0
nagios_services_checked_total{check_type="passive"} 0
```

I'm not entirely sure, but I bet the `UpdateCommonMetrics` call below that has some ordering issues. The mapping from the slice to the actual variables seem legit (although why we do not use the `60M` metrics to make a 60 minutes bucket escapes m e here), and it seems the call to the function itself is in order, but darn it that's confusing to review...

**Comment by anarcat** [comment]
interestingly, I have just restarted the exporter, and boom, the counters shot back up, then started to go down again. you can see that phenomenon in this screenshot here:

![image](https://github.com/wbollock/nagios_exporter/assets/796623/02db9d88-017b-4d57-967b-a524e81e777e)

the "blank" is when I rebooted the server for a small config change... you can see the counters going all the way down until ~03:20. then I restarted the exporter again, this time with `-log.level debug` and zoom, the counters shot back up again but then, mysteriously, *they stayed up*! [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug)?

here's the `docker-compose.yml` I use to start the exporter:

```
services:
  nagios_exporter:
    image: ghcr.io/wbollock/nagios_exporter
    network_mode: "host"
    ports: 
      - "9927:9927"
    restart: unless-stopped
    volumes:
      - "/etc/prometheus-nagios-exporter/:/etc/prometheus-nagios-exporter/:ro"
      - "/usr/sbin/icingastats:/usr/sbin/icingastats:ro"
      - "/etc/icinga/icinga.cfg:/etc/icinga/icinga.cfg:ro"
      - "/var/lib/icinga/status.dat:/var/lib/icinga/status.dat:ro"
      - "/etc/ld.so.cache:/etc/ld.so.cache:ro"
      - "/lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro"
      - "/lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro"
      - "/lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro"
      - "/lib/x86_64-linux-gnu/libz.so.1:/lib/x86_64-linux-gnu/libz.so.1:ro"
    user: "10000:10000"
    command: 
      - "-nagios.stats_binary"
      - "/usr/sbin/icingastats"
      - "-nagios.config_path"
      - "/etc/icinga/icinga.cfg"
      - "-log.level"
      - "debug"
```

... and yes, i know how gruesome and unholy those volume maps look. i console myself with the idea this is all temporary horrors for now, and i sincerely (and naively) hope it really is temporary. :p
```

**Comment by wbollock** [comment]
I don't have an Iciginia setup and haven't used it before, any chance you could provide a full docker-compose file with Icigina already setup?

Also the most supported version of this exporter is using the NagiosXI API, I know it doesn't help for your use case but parsing any of those text `stats` outputs sucks :(

**Comment by anarcat** [comment]
> I don't have an Iciginia setup and haven't used it before, any chance you could provide a full docker-compose file with Icigina already setup?

That would be Hard™. Our setup is some old convoluted, decades-old "thing" that has been mostly manually managed since earlier in this millenia. I suspect it thinks it will survive until the next, but I'm hell bent of cleaning up that legacy shit, so I'm not especially excited about reproducing this setup. :)

> Also the most supported version of this exporter is using the NagiosXI API, I know it doesn't help for your use case but parsing any of those text `stats` outputs sucks :(

Yeah, I understand.  It's a truly bizarre bug: it's as if some stats "stick" to the exporter.

Is it possible the command output gets cached somehow?

Here is, for example, a nearly simultaneous output from the exporter debug logs and manually running `icingastats`. Log line:

```
nagios_exporter_1  | time="2023-12-13T19:09:15Z" level=debug msg="Queried nagiostats: NAGIOSVERSION,96,0,0,96,0,0,0,0,4403,0,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
```

actual command run:

```
root@hetzner-hel1-01:/etc/prometheus-nagios-exporter# date;  icingastats -d NAGIOSVERSION,NUMHOSTS,NUMHSTACTCHK60M,NUMHSTPSVCHK60M,NUMHSTUP,NUMHSTDOWN,NUMHSTUNR,NUMHSTFLAPPING,NUMHSTDOWNTIME,NUMSERVICES,NUMSVCACTCHK60M,NUMSVCPSVCHK60M,NUMSVCOK,NUMSVCWARN,NUMSVCUNKN,NUMSVCCRIT,NUMSVCFLAPPING,NUMSVCDOWNTIME,NUMHSTACTCHK1M,NUMHSTACTCHK5M,NUMHSTACTCHK15M,NUMHSTPSVCHK1M,NUMHSTPSVCHK5M,NUMHSTPSVCHK15M,NUMSVCACTCHK1M,NUMSVCACTCHK5M,NUMSVCACTCHK15M,NUMSVCPSVCHK1M,NUMSVCPSVCHK5M,NUMSVCPSVCHK15M,AVGACTHSTLAT,MINACTHSTLAT,MAXACTHSTLAT,AVGACTHSTEXT,MINACTHSTEXT,MAXACTHSTEXT,AVGACTSVCLAT,MINACTSVCLAT,MAXACTSVCLAT,AVGACTSVCEXT,MINACTSVCEXT,MAXACTSVCEXT -m -D,
Wed Dec 13 19:09:17 UTC 2023
NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,4252,0,4383,17,0,3,0,0,20,93,96,0,0,0,255,1302,3672,0,0,0,229,110,417,99,29,198,143,0,371,409,28,5936,
```

The output is suspiciously different. Even more suspicious, it has not changed at all in many, many scrapes. Here's an example:

```
root@hetzner-hel1-01:/etc/prometheus-nagios-exporter# docker-compose  logs | grep -o 'Queried nagiostats:.*' | sort | uniq -c | sort -n | tail -10
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,0,10,96,0,0,0,0,82,1558,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,0,29,96,0,0,0,0,234,1703,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,0,48,96,0,0,0,0,386,1847,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,0,67,96,0,0,0,0,540,1987,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,10,83,96,0,0,0,82,693,1987,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,841,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      1 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,984,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
      2 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,1987,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
     30 Queried nagiostats: NAGIOSVERSION,96,96,0,96,0,0,0,0,4403,2002,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
    898 Queried nagiostats: NAGIOSVERSION,96,0,0,96,0,0,0,0,4403,0,0,4380,20,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,202,77,332,105,28,225,140,0,352,410,22,6381,\n"
```

There we see almost a thousand scrapes have logged an identical stats line, which sounds utterly impossible.

So now my bet is on the command output being cached.

**Comment by anarcat** [comment]
> parsing any of those text stats outputs sucks

oh and about that: oh yeah, that's horrible! :) One thing I think could help is if you would make some sort of struct for this datastructure. Just aligning all those fields nicely in one data structure would at least make it easier to compare with the arguments passed to the command but more crucially make it much more sturdier as you pass that structure around.

**Comment by anarcat** [comment]
> So now my bet is on the command output being cached.

An update on that: i've been able to reproduce the issue outside of the exporter. Just running the icingastats command within the same container with docker-compose yields exactly the same result, so I don't think the exporter is to blame here, but my janky container setup probably is.

Closing.

**Comment by anarcat** [comment]
for those following at home and curious what the error was, this is the correct docker-compose.yml file:

```
services:
  nagios_exporter:
    image: ghcr.io/wbollock/nagios_exporter
    network_mode: "host"
    ports: 
      - "9927:9927"
    restart: unless-stopped
    volumes:
      - "/etc/prometheus-nagios-exporter/:/etc/prometheus-nagios-exporter/:ro"
      - "/usr/sbin/icingastats:/usr/sbin/icingastats:ro"
      - "/etc/icinga/icinga.cfg:/etc/icinga/icinga.cfg:ro"
      - "/var/lib/icinga/:/var/lib/icinga/:ro"
      - "/etc/ld.so.cache:/etc/ld.so.cache:ro"
      - "/lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro"
      - "/lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro"
      - "/lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro"
      - "/lib/x86_64-linux-gnu/libz.so.1:/lib/x86_64-linux-gnu/libz.so.1:ro"
    user: "10000:10000"
    command: 
      - "-nagios.stats_binary"
      - "/usr/sbin/icingastats"
      - "-nagios.config_path"
      - "/etc/icinga/icinga.cfg"
      - "-log.level"
      - "debug"
```

The error was this volume configuration:

```
    volumes:
      - "/var/lib/icinga/status.dat:/var/lib/icinga/status.dat:ro"
```

That works for the first run, as Docker bind-mounts that very file inside the container, but the second nagios/icinga updates it, it actually move a *new* file in place, which the container never sees because it's a different inode. The fix is to mount the whole directory instead:

```
    volumes:
      - "/var/lib/icinga/:/var/lib/icinga/:ro"
```

Sorry for the noise!
